### PR TITLE
Add some unit test issue #1

### PR DESCRIPTION
**Pull request by NyorJa**
I did not manage to cover all classes but hope it helps with the coverage since i find that its hard to pass the other conditions or maybe i do lack some test data. Please add label "hacktoberfest-accepted" if merge. Thanks. Glad to contribute in this project.

### CODE REVIEW

**Comment by DyspC** [comment]
Hello there, 

First thanks for the PR, the jacoco integration is great though not critical.

Could you please rebase the gradle / java parts on the 'testing' branch and use the test data you'll find there in your test constants? Your lyrics.txt file (with Indonesian if I'm not mistaken) is good for language processing but a bit too much of an edge case because the syllable split is based on how Japanese is written.  
You can use Assert.equals as a failure trigger since the issue is about preventing unseen regressions rather than boosting code coverage.

(Poking #1 for navigation sakes)

**Comment by NyorJa** [comment]
oops..i commited the lyrics..ill remove that.sorry for that

**Comment by NyorJa** [comment]
I will add another test since I do have the resources

**Comment by NyorJa** [comment]
Hi @DyspC ,

Please check [more test](https://github.com/DyspC/LyricsPrimer/pull/3/commits/2d64dae2e5bfe66f239f3d9d9333cc1bc2dd122f). If accepted please add label "hacktoberfest-accepted"

**Comment by DyspC** [comment]
That looks alright thank you

**Pull request merged**
